<!doctype html><html><head><meta charset="utf-8" /><title>

    At Runtime Editor r14

</title></head><body><script>

// ----------------------------------------------------------------
// Definitions
// ----------------------------------------------------------------

    var core;

    core = {};

// --------

    function Define_get() {

        function Proto_get( key ) {

            // I use core here from the global scope, instead of passing it along, for the time being. It would create caching in ways I cannot forsee how it might affect the rest of the system... But we could pass core along and perhaps use that as a method to recover from a last failure?
            return core[ key ];

        }

        return Proto_get;

    }

    
    core[ "get" ] = Define_get();
    
// --------

    function Define_set() {

        function Proto_set( key, value ) {

            core[ key ] = value;

        }

        return Proto_set;

    }

    core[ "set" ] = Define_set();

// --------

    function Define_isUndefined() {

        function Proto_isUndefined( value ) {

            return ( typeof value === "undefined" );

        }

        return Proto_isUndefined;

    }

    core.set(
        "isUndefined",
        Define_isUndefined()
    );

// --------

    function Define_isFunction() {

        function Proto_isFunction( value ) {

            return (typeof value === "function");

        }

        return Proto_isFunction;

    }

    core.set(
        "isFunction",
        Define_isFunction()
    );

// --------
    
    function Define_log() {

        function Proto_log() {

            console.log.apply( console, arguments );

        }

        return Proto_log;

    }

    core.set(
        "log",
        Define_log()
    );

// --------

    function Define_logError() {

        function Proto_logError( err ) {

            core.set( "error_state", true );

            throw new Error( err );

        }

        return Proto_logError;

    }

    core.set(
        "logError",
        Define_logError()
    );

// --------

    function Define_rememberCurrentState() {

        function Proto_rememberCurrentState() {

            core.set( "lastStableBody", document.body );

        }

        return Proto_rememberCurrentState;

    }

    core.set(
        "rememberCurrentState",
        Define_rememberCurrentState()
    );

// --------

    function Define_constructErrorBody() {

        function Proto_constructErrorBody() {

            var err_body = document.createElement( "body" );

            err_body.style.backgroundColor = "#c33";
            err_body.style.color = "#fff";

            core.set( "error_body", err_body );

        }

        return Proto_constructErrorBody;

    }

    core.set(
        "constructErrorBody",
        Define_constructErrorBody()
    );

// --------

    function Define_errorState() {

        function Proto_errorState() {

            return core.get( "error_state" );

        }

        return Proto_errorState;

    }

    core.set(
        "errorState",
        Define_errorState()
    );

// -------

    // We start our first entry here I guess?
    core.rememberCurrentState();

    // Might as well get this started?
    core.constructErrorBody();

// ----------------------------------------------------------------
// This is where dependencies start
// ----------------------------------------------------------------

    function Define_faultOnError( constructErrorBody, logError ) {

        function Proto_faultOnError( err ) {

            var err_body,
                err_container,
                err_message;

            if ( ! core.get( "error_body_is_contructed" ) ) {

                constructErrorBody();

                core.set( "error_body_is_contructed", true );

            }
            
            err_body = core.get( "error_body" );

            err_container = document.createElement( "pre" );

            err_message = document.createTextNode( err );

            err_container.appendChild( err_message );

            err_body.appendChild( err_container );

            document.body = err_body;

            logError( err );

        }

        return Proto_faultOnError;

    }

    core.set(
        "faultOnError",
        Define_faultOnError(
            core.get( "constructErrorBody" ),
            core.get( "logError" )
        )
    );

// --------

    function Define_attempt( errorState, faultOnError, rememberCurrentState ) {

        function Proto_attempt( toAttempt, args ) {

            // Do a check here if we're not already in an error state? Would make some sense...
            // ---- Logic being that if the current state is already garbled, we shouldn't probably keep trying new stuff. Recover first, then try.
            if ( errorState() ) {

                //#NOTE: Use my formatizer to contruct these messages? like: formatizer( "{@1:error} - {@2:suggestion}", ERR_CORE_UNSTABLE, "core.recoverFromError" )
                faultOnError( "Core is unstable, no further attempts can be made at this point.\nTry 'core.recoverFromError()'" );

            }

            // ----

            rememberCurrentState();

            try {

                return toAttempt.apply( null, args );

            } catch ( err ) {

                faultOnError( err );

            }

        }

        return Proto_attempt;

    }

    core.set(
        "attempt",
        Define_attempt(
            core.get( "errorState" ),
            core.get( "faultOnError" ),
            core.get( "rememberCurrentState" )
        )
    );

// --------

    function Define_prepRequirement( isUndefined, faultOnError ) {

        function Proto_prepRequirement( requirement, index, requirements ) {

            if ( isUndefined( core[ requirement ] ) ) {

                faultOnError( "unrecognised resource: " + requirement );

            }

            requirements[ index ] = core.get( requirement );

        }

        return Proto_prepRequirement;

    }

    core.set(
        "prepRequirement",
        Define_prepRequirement(
            core.get( "isUndefined" ),
            core.get( "faultOnError" )
        )
    );

// --------

    function Define_register( core, faultOnError, attempt, log, isUndefined, isFunction, prepRequirement ) {

        function Proto_register( name, callback, requirements, test ) {

            if ( isUndefined( name ) ) {

                //#NTWT
                //#NOTE: Also should probably stick this into a constant or something?
                faultOnError( "Call to register with an undefined name" );

            }

            if ( isUndefined( callback ) ) {

                //#NTWT
                //#NOTE: Also should probably stick this into a constant or something?
                faultOnError( "Call to register with an undefined callback function" );

            }

            if ( ! isFunction( callback ) ) {

                //#NTWT
                //#NOTE: Also should probably stick this into a constant or something?
                faultOnError( "Call to register with a callback that is not a function" );

            }

            if ( isUndefined( requirements ) ) {

                //#NTWT
                //#NOTE: Also should probably stick this into a constant or something?
                faultOnError( "Call to register with an undefined array of requirements" )

            }

            requirements.forEach( prepRequirement );

            log( "begin registering:", name );

            core[ name ] = attempt( callback, requirements );

            log( "done registering:", name );

            if ( ! isUndefined( test ) && isFunction( test ) ) {

                attempt( test );

            }

        }

        return Proto_register;

    }

    core.set(
        "register",
        Define_register(
            core,
            core.get( "faultOnError" ),
            core.get( "attempt" ),
            core.get( "log" ),
            core.get( "isUndefined" ),
            core.get( "isFunction" ),
            core.get( "prepRequirement" )
        )
    );

// --------

    function Define_recoverFromError( constructErrorBody, getLastStableState ) {

        function Proto_recoverFromError() {

            constructErrorBody();

            document.body = core.get( "lastStableBody" );

            core.set( "error_state", false );

        }

        return Proto_recoverFromError;

    }

    core.set(
        "recoverFromError",
        Define_recoverFromError(
            core.get( "constructErrorBody" ),
            core.get( "getLastStableState" )
        )
    );

// --------

</script></body></html>